non_root_user: "{{ lookup('env', 'USER') }}"

# base domain to use
cluster_domain: "{{ lookup('env', 'CLUSTER_DOMAIN') | default('ostest.test.metalkube.org', true) }}"

# allow the nic model to be overridden
libvirt_nic_model: virtio

# These defaults are used if there are no flavor-specific
# overrides configured.
default_disk: 50
default_memory: 8192
default_vcpu: 4
extradisks: false
virtualbmc_base_port: 6230
flavors:
  node:
    memory: '{{node_memory|default(default_memory)}}'
    disk: '{{node_disk|default(default_disk)}}'
    vcpu: '{{node_vcpu|default(default_vcpu)}}'
    extradisks: '{{extradisks|bool}}'

# An optional prefix for node names
ironic_prefix: ""

# Ironic scalability vars
default_vm_id: 1
default_num_vms: 1
default_num_nodes: 2
num_nodes: "{{ lookup('env', 'NUM_NODES')|default(default_num_nodes) }}"
vm_id_local: "{{ lookup('env', 'VM_ID')|default(default_vm_id) }}"
num_vms: "{{ lookup('env', 'NUM_VMS')|default(default_num_vms) }}"

# Customized index for node names
custom_index: "{{ (vm_id_local|int - 1) * (num_nodes)|int }}"

baremetal_network_cidr_v4: "{{ lookup('env', 'EXTERNAL_SUBNET_V4')|default('', true) }}"
baremetal_network_cidr_v6: "{{ lookup('env', 'EXTERNAL_SUBNET_V6')|default('', true) }}"
virsh_dhcp_v4_start: "{{ lookup('env', 'VIRSH_DHCP_V4_START')|default('', true) }}"
virsh_dhcp_v4_end: "{{ lookup('env', 'VIRSH_DHCP_V4_END')|default('', true) }}"
virsh_dhcp_v6_start: "{{ lookup('env', 'VIRSH_DHCP_V6_START')|default('', true) }}"
virsh_dhcp_v6_end: "{{ lookup('env', 'VIRSH_DHCP_V6_END')|default('', true) }}"
#scalability: "{{ lookup('env', 'IRONIC_SCALABILITY_TEST')|default('', false) }}"


# Set this to `false` if you don't want your vms
# to have a VNC console available.
enable_vnc_console: true

# Path for volume storage
libvirt_volume_path: "{{ working_dir }}/pool"

# These ensure we're using privileged virt, so VMs persist over reboot
libvirt_uri: qemu:///system
ssh_user: root

# Describe our virtual networks.  These networks will be attached to
# the vm nodes in the order in which they are defined with the following caveats:
#   *  The first bridge network defined will be used for pxe booting
manage_baremetal: "{% if vm_id_local == 1 %}y{% else %}n{% endif %}"
networks:
  - name: provisioning
    bridge: provisioning
    forward_mode: bridge
  - name: baremetal
    bridge: baremetal
    forward_mode: "{% if manage_baremetal == 'y' %}nat{% else %}bridge{% endif %}"
    address_v4: "{{ baremetal_network_cidr_v4|nthhost(vm_id_local)|default('', true) }}"
    netmask_v4: "{{ baremetal_network_cidr_v4|ipaddr('netmask') }}"
#"{% if scalability == 'false' %}
#    dhcp_range_v4:
#      - "{{ virsh_dhcp_v4_start }}"
#      - "{{ virsh_dhcp_v4_end }}"
#{% endif %}"
    address_v6: "{{ baremetal_network_cidr_v6|nthhost(1)|default('', true) }}"
    prefix_v6: "{{ baremetal_network_cidr_v6|ipaddr('prefix') }}"
    dhcp_range_v6:
      - "{{ virsh_dhcp_v6_start }}"
      - "{{ virsh_dhcp_v6_end }}"
    nat_port_range:
      - 1024
      - 65535
    domain: "{{ cluster_domain }}"
    dns:
      hosts: "{{dns_extrahosts | default([])}}"
      forwarders:
        # Use 127.0.0.1 unless only IPv6 is enabled
        - domain: "apps.{{ cluster_domain }}"
          addr: "{% if baremetal_network_cidr_v4|ipv4 != False %}127.0.0.1{% else %}::1{% endif %}"
      srvs: "{{dns_externalsrvs | default([])}}"
